# Generated by Django 4.2.2 on 2023-06-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Patient Name')),
                ('patient_phone', models.CharField(max_length=10, verbose_name='Patient Phone')),
                ('patient_email', models.EmailField(max_length=254, verbose_name='Patient Email')),
                ('doctor', models.CharField(max_length=255, verbose_name='Doctor')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
                ('booked_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
