# Generated by Django 4.2.2 on 2023-06-14 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_specialization', models.CharField(max_length=255)),
                ('doctor_image', models.ImageField(upload_to='doctors')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.department')),
            ],
        ),
    ]
